# Generated by Django 4.2.7 on 2023-11-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_email', models.EmailField(max_length=254)),
                ('p_phone', models.CharField(max_length=10)),
                ('p_message', models.CharField(max_length=255)),
                ('contact_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
